version: '3.6'
services:
  keycloak-ktor:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: 'keycloak-ktor'
    ports:
      - "127.0.0.1:58081:8080"
    environment:
      - KEYCLOAK_IMPORT=/tmp/ktor-realm.json
      - KEYCLOAK_ADMIN=ktor-admin
      - KEYCLOAK_ADMIN_PASSWORD=secret
      - DB_VENDOR=H2
    entrypoint: /bin/bash /bootstrap.sh
    volumes:
      - ./keycloak/bootstrap.sh:/bootstrap.sh
      - ./keycloak/ktor-realm.json:/tmp/ktor-realm.json

networks:
  default:
    name: ktor-network
