GET {{ktor-poc-url}}
Content-Type: text/plain

> {%
    client.log("=======================")
    client.log("status: " + response.status)
    client.log("profile:")
    client.log("email: " + response.body["email"])
    client.log("firstName: " + response.body["firstName"])
    client.log("lastName: " + response.body["lastName"])
    client.log("=======================")
    client.test("check profile receiving status", function(){
      client.assert(response.status == 200, "Response status should be 200")
    })
%}
